name: Build Latest

on:
  push:
  workflow_dispatch: {}
  pull_request:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '0 4 * * *'

jobs:
  build_tycho_J8_on_J11:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: 11
      - name: Build
        uses: GabrielBB/xvfb-action@v1.5
        with:
          run: mvn clean verify
      - name: Get log
        id: vars
        run: echo ::set-output name=x::$(cat ./org.xtext.example.mydsl1.ui.tests/target/work/data/.metadata/.log)
      - name: Test output
        run: echo ${{ steps.vars.outputs.x }}
